### ISSUE TITLE
При нажатии Enter меняется раскладка для последнего введенного символа

### ISSUE THREAD

**Issue by Serega124** [T1mL3arn/Duolingo-input-language-switcher#2]
При нажатии Enter меняется раскладка для последнего введенного символа.

![изображение](https://user-images.githubusercontent.com/5006548/64435768-c004f680-d0cb-11e9-81f0-2955e4d997e6.png)
![изображение](https://user-images.githubusercontent.com/5006548/64435869-ea56b400-d0cb-11e9-8da6-2f8022275729.png)

**Comment by T1mL3arn** [comment]
@Serega124 исправлено.
